"""empty message

Revision ID: 24ab10f5fbd9
Revises: 
Create Date: 2017-11-17 21:27:03.818241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ab10f5fbd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_ibfk_1', 'events', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('events_ibfk_1', 'events', 'clueponies', ['event_id'], ['id'])
    # ### end Alembic commands ###
