"""empty message

Revision ID: 351276e23da4
Revises: d7ba590beff7
Create Date: 2017-11-23 13:35:40.714462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351276e23da4'
down_revision = 'd7ba590beff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
